apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rcevjt50p-go 
  janus-idp.io/tekton: rcevjt50p-go
  backstage.io/kubernetes-id: rcevjt50p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rcevjt50p-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  